# Generated by Django 4.2.2 on 2023-07-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('content', models.TextField(max_length=1000, verbose_name='название')),
                ('preview', models.ImageField(upload_to='', verbose_name='изображение')),
                ('date_of_creation', models.DateTimeField(verbose_name='дата создания')),
                ('sign_of_publication', models.CharField(max_length=150, verbose_name='опубликовано')),
            ],
        ),
    ]
