# Generated by Django 4.2.2 on 2023-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_sign_of_publication_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.CharField(verbose_name='дата создания'),
        ),
    ]
